"use strict";
const projectList = [
  {
    image: "./images/zach_portrait_color.jpg",
    id: "about",
    font: "Quicksand-Bold",
    title: "Hello.  Welcome!",
    paragraph:
      "<p class='paragraphs'>My name is Zachary John Kline.  </br>By profession, I am <span id='profession-phrase'>a</span></p><p id='profession'>design professional.</p><p class='instructions'>Scroll to view my portfolio!</p>",
    date: "",
    titleColor: "rgb(31, 29, 50)",
    infoColor: "rgb(31, 29, 50)",
    bgBlockColor: "rgb(31, 29, 50)",
    bgColorLS: "linear-gradient(180deg, lightgray, white)",
    bgColor: "linear-gradient(0deg, lightgray, white)",
  },
  // {
  //   image: "./images/pop_sugar.png",
  //   id: "pop-sugar",
  //   title: "Pop Sugar",
  //   paragraph:
  //     "<p>Cute and sweet, Pop Sugar was a brand created for a local stationery company to extend the age range of their current consumer, but not stray too far from their brand identity.</p>",
  //   date: "January 2019 - May 2019",
  //   titleColor: "#410053",
  //   infoColor: "#410053",
  //   bgBlockColor: "#410053",
  //   bgColorLS: "linear-gradient(90deg, #f0eeee, #e09ec2)",
  //   bgColor: "linear-gradient(0deg, #f0eeee, #e09ec2)",
  // },
  // {
  //   image: "./images/scentins.png",
  //   id: "scentins",
  //   title: "Scentins",
  //   paragraph:
  //     "<p>The Scentins brand was created for an emerging stationery company, centered around fruit scents and adorable characters.</p>",
  //   date: "December 2018 - March 2019",
  //   titleColor: "#1a771f",
  //   infoColor: "#1a771f",
  //   bgBlockColor: "#1a771f",
  //   bgColorLS: "linear-gradient(270deg, #fffaaa, #bfdd46)",
  //   bgColor: "linear-gradient(0deg, #fffaaa, #bfdd46)",
  // },
  // {
  //   image: "./images/squibblers.png",
  //   id: "squibblers",
  //   title: "Squibblers",
  //   paragraph:
  //     "<p>Squibblers was a brand of spring and summer related characters for kids that became squishy chalk holders for their line of sidewalk chalk.</p>",
  //   date: "December 2018 - February 2019",
  //   titleColor: "#1e71b8",
  //   infoColor: "#1e71b8",
  //   bgBlockColor: "#1e71b8",
  //   bgColorLS: "linear-gradient(90deg, #1e71b870, #fffac1)",
  //   bgColor: "linear-gradient(0deg, #1e71b870, #fffac1)",
  // },
  {
    image: "./images/leisurearts.jpg",
    id: "leisure-arts",
    font: "Quicksand-Bold",
    title: "Leisure Arts",
    paragraph:
      "<p>The creativity and inspiration of the folks from Leisure Arts is second to none and working with them continues to be an exciting adventure!</p>",
    date: "March 2019 - Present",
    titleColor: "#397e84",
    infoColor: "#397e84",
    bgBlockColor: "#397e84",
    bgColorLS: "linear-gradient(90deg, #afdae1, #d6ebea)",
    bgColor: "linear-gradient(0deg, #afdae1, #d6ebea)",
    // titleColor: "rgb(31, 29, 50)",
    // infoColor: "rgb(31, 29, 50)",
    // bgBlockColor: "rgb(31, 29, 50)",
    // bgColorLS: "linear-gradient(180deg, lightgray, white)",
    // bgColor: "linear-gradient(0deg, lightgray, white)",
  },
  {
    image: "./images/scentins_company.jpg",
    id: "scentins",
    font: "Quicksand-Bold",
    title: "Scentins",
    paragraph:
      "<p>I worked with Scentins on several product lines to bring multi-sensory experiences to toys and stationery.</p>",
    date: "August 2019 - June 2022",
    titleColor: "#153917",
    infoColor: "#1a771f",
    bgBlockColor: "#153917",
    // bgColorLS: "linear-gradient(270deg, #fffaaa, #bfdd46)",
    // bgColor: "linear-gradient(0deg, #fffaaa, #bfdd46)",
    // titleColor: "rgb(31, 29, 50)",
    // infoColor: "rgb(31, 29, 50)",
    // bgBlockColor: "rgb(31, 29, 50)",
    // bgColorLS: "linear-gradient(180deg, lightgray, white)",
    // bgColor: "linear-gradient(0deg, lightgray, white)",
    // titleColor: "#F73CA8",
    // titleColor: "#610054",
    // infoColor: "#B42B7A",
    // bgBlockColor: "#610054",
    // bgColorLS:
    //   "linear-gradient(270deg, #FFBCBC 10%, #E0C6FF 20%, #D3FFFF 50%, #FAF7CA 70%, #FCD0BF 80%, #FDB9B9 90%)",
    // bgColor:
    //   "linear-gradient(0deg, #FFBCBC 10%, #E0C6FF 20%, #D3FFFF 50%, #FAF7CA 70%, #FCD0BF 80%, #FDB9B9 90%)",
    bgColorLS: "linear-gradient(90deg, #ddf0a5, #89be8a)",
    bgColor: "linear-gradient(0deg, #ddf0a5, #89be8a)",
  },
  {
    image: "./images/weveel.jpg",
    id: "weveel",
    font: "Quicksand-Bold",
    title: "WeVeel",
    paragraph:
      "<p>The countless product concepts, character illustrations, 3D renders, package designs, and package prototypes I completed for this company were as fun to create as they were to see in stores!</p>",
    date: "August 2012 - March 2019",
    titleColor: "#00abe9",
    infoColor: "#00abe9",
    bgBlockColor: "#00abe9",
    bgColorLS: "linear-gradient(90deg, #c0daed, #e2f1fb)",
    bgColor: "linear-gradient(0deg, #c0daed, #e2f1fb)",
    // titleColor: "rgb(31, 29, 50)",
    // infoColor: "rgb(31, 29, 50)",
    // bgBlockColor: "rgb(31, 29, 50)",
    // bgColorLS: "linear-gradient(180deg, lightgray, white)",
    // bgColor: "linear-gradient(0deg, lightgray, white)",
  },
  {
    image: "./images/zeezee.jpg",
    id: "zeezee",
    font: "Quicksand-Bold",
    title: "Zee Zee Design",
    paragraph:
      "<p class='paragraphs'>In partnering with Zee Zee Design LLC, I helped them build their website, their prototyping processes and procedures, and their dieline scripting.</p>",
    date: "June 2018 - Present",
    titleColor: "black",
    infoColor: "black",
    bgBlockColor: "black",
    bgColorLS: "linear-gradient(180deg, lightgray, white)",
    bgColor: "linear-gradient(0deg, lightgray, white)",
  },
];
